Wr/nuts
salesforcecli/plugin-config pull request #75
Opened 2021-03-08 22:16 UTC by WillieRuemmele

### What does this PR do?
adds NUTs
### What issues does this PR fix or reference?
@W-8856595@

2021-03-08 22:27 UTC, peternhale commented on test/commands/config/set.nut.ts
> +    describe('apiVersion', () => {
@WillieRuemmele, is it necessary to verify all of the valid configs for both positive and negative values? One would think that unit tests would be covering that sort of thing.

2021-03-08 22:38 UTC, mshanemc requested changes
As part of this PR, can you do the circle stuff

1. adding linux/win NUTs to the config.yml (use plugin-user as a template?)
2. Add any required env vars on circle (there may not be any if there's no auth/orgs in here)

That verifies that these will pass on linux and windows

2021-03-08 22:47 UTC, WillieRuemmele commented on test/commands/config/set.nut.ts
> +    describe('apiVersion', () => {
I added one happy/sad path for each config value, I wanted to make sure the messaging was correct for each one. If you think that's overkill we can talk about removing it

2021-03-08 22:51 UTC, peternhale commented on test/commands/config/set.nut.ts
> +    describe('apiVersion', () => {
Are all these covered in unit tests? If not I would suggest getting this kind of coverage in unit tests and leave NUTs to cover a sampling.

2021-03-08 22:53 UTC, WillieRuemmele commented on test/commands/config/set.nut.ts
> +    describe('apiVersion', () => {
I'm not sure, but I figured more rather than less, and once you're testing one it becomes pretty easy to test the rest 🤷‍♂️

2021-03-10 16:51 UTC, shetzel approved these changes

2021-03-10 17:10 UTC, amphro requested changes

2021-03-10 17:10 UTC, amphro commented on test/commands/config/get.nut.ts
> +      delete res?.stack;
Why not just do a partial check rather than deleting then doing a deep equal?

2021-03-10 17:10 UTC, amphro commented on test/commands/config/get.nut.ts
> +        warnings: ['apiVersion configuration overridden at "51.0"'],
Same here. Maybe just check that the warning is in the warnings list? If we ever add more warnings, let's say at the CLI level which is valid, it will cause this test to fail, which is not desirable.

2021-03-10 17:10 UTC, amphro commented on test/commands/config/get.nut.ts
> +        warnings: ['apiVersion configuration overridden at "51.0"'],
This is another reason why I don't like deep equals. This warning has nothing to do with this test. I would rather you just check the results object.

2021-03-10 17:10 UTC, amphro commented on test/commands/config/set.nut.ts
> +          // value will always be a string
is a shame. I thought we use to parse the value based on the type?

2021-03-10 17:10 UTC, amphro commented on test/commands/config/set.nut.ts
> +          'Setting variables must be in the format <key>=<value> or <key>="<value with spaces>" but found randomKey.',
Ditto with all of these too.

2021-03-10 19:35 UTC, amphro approved these changes

2021-03-17 16:03 UTC, merged